### ISSUE TITLE
Define final configuration to run 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/spc-hpc-pipeline#10]
Currently, the pipeline has been designed to run as described as shown in [here](https://github.com/alan-turing-institute/dymechh/issues/26#issuecomment-1297209992).  However, given the discussion on that issue the final setup will be something like described in [here](https://github.com/alan-turing-institute/dymechh/issues/26#issuecomment-1300850030), which the final year to be decided.
 
I think we could try the best-case scenario (2080?) for a couple of LADs and measure how long it will take to run and its costs. This needs direct input from Ruth, Hadrien.

**Comment by HSalat** [comment]
My take on the subject is that we should try to limit ourselves to 5 dates (including 2011 and 2020), as there are further steps to prepare the data for the full SPC process once these data are produced. Ruth to decide which dates that would be. Just bear in mind that we have no real control on the quality of the projections.

**Comment by RuthBowyer** [comment]
Hey there - I think the ideal would be one date several decades in the future, but modelled on the different shared socioeconomic pathways, if possible (as [here](https://github.com/alan-turing-institute/dymechh/issues/26#issuecomment-1302081058)) - however if not possible and its the same socioeconomic projection just temporally different, then 2040, 2060, 2080 would be great

**Comment by crangelsmith** [comment]
Hi both! Could you advise how this would look like from the configuration files in [here](https://github.com/alan-turing-institute/spc-hpc-pipeline/tree/main/scripts/scp)? I don't see any obvious variable for step size in the simulation.

**Comment by HSalat** [comment]
Hi! As far as I know, the step size is hard-coded as one year (the output for every year until the specified date is created in the same folder when running the ssm scripts). Maybe turning the file writing off for years we don't want in a separate branch could accelerate the process?

**Comment by crangelsmith** [comment]
I've been looking a this today and looks like the steps that create the intermediate years (run_ssm.py and run_ssm_h.py) are fairly fast to run -seconds-, so we might not have to worry too much about that. The assignment process is the lengthy one, and it's done individually per year and we can configure it with the json files. 

Now, a problem I've found is that the household microsimulation (run_ssm_h.py script) uses [these ONS projections](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationprojections/datasets/householdprojectionsforenglanddetaileddataformodellingandanalysis/2016based/detailedtablesstage1and2.zip%22) to create the datasets, and they have an upper limit for 2042. If we try to go futher the code breaks for lack of data to project. 

Do you have an idea of how to work around this?

**Comment by HSalat** [comment]
All right, then we could choose 2012, 2020, 2022, 2032 and 2042 @RuthBowyer . What I can do is add a mechanic to also grow the population in numbers within the new version of SPC. It will have to be based on some other projections once they become available (based on the new census that is).

**Comment by RuthBowyer** [comment]
> All right, then we could choose 2012, 2020, 2022, 2032 and 2042 @RuthBowyer . What I can do is add a mechanic to also grow the population in numbers within the new version of SPC. It will have to be based on some other projections once they become available (based on the new census that is).

Sorry for so reply, I wanted to chat it over with Gavin first - that sounds great, thank you!! And in future I will think about how we might instead integrate the shared socioeconomic pathway data projections

**Comment by RuthBowyer** [comment]
That sounds good! Is Northern Ireland included out of interest?

**Comment by RuthBowyer** [comment]
Great, thank you!
