### ISSUE TITLE
Running microsimulation in Scotland is broken 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/spc-hpc-pipeline#14]
Running in Scotland LADs give the following errors. 

[stdout.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10121807/stdout.4.txt)
[stderr.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10121808/stderr.7.txt)

**Comment by crangelsmith** [comment]
One of the errors when running Scotland is created by the VM reaching its limit on disk space, this has been sorted by upgrading the VM in [ef54576](https://github.com/alan-turing-institute/spc-hpc-pipeline/pull/17/commits/ef54576cebff0323f7c5e4c75c2dd2f077b66b06) and making sure to run the tests for `household_microsynth` beforehand so all the files needed in step 1 are dowloaded and unzipped [17d41df](https://github.com/alan-turing-institute/spc-hpc-pipeline/pull/17/commits/17d41df41040c09420942251fcaa05cc7460b2da) in PR #17.

There is still an error when running `scripts/run_ssm.py` on the microsimulation package. I've attached the errors I get now when running from PR #17.

[stdout_scotland_5Dec2022.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10155256/stdout_scotland_5Dec2022.txt)
[stderr_scotland_5Dec2022.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10155257/stderr_scotland_5Dec2022.txt)

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/UKCensusAPI/commit/19b541898f82b0a982433eaba44b8a217e1235e9 This could be a potential fix! Testing...
