### ISSUE TITLE
Containers aren't deleted

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/spc-hpc-pipeline#15]
https://github.com/alan-turing-institute/spc-hpc-pipeline/blob/4207caa7b75ceb1250928c84c8bfe9bd1cc82dc1/spc-hpc-client.py#L506

Just needs `blob_service_client.delete_container(input_container_name)` added back - must have been lost at some point.

**Comment by crangelsmith** [comment]
But i don't think we want to delete the containers? that is where all the output simulated data will be stored.

**Comment by AoifeHughes** [comment]
I wasn't sure if the end plan was to move the data somewhere else?

**Comment by crangelsmith** [comment]
Maybe, but it would be a shame that the container gets deleted at the end of the job without having downloaded/moved it. I think is safer that we delete by hand if we feel we have to.

**Comment by AoifeHughes** [comment]
Makes sense - will remove the confusing print statement
