### ISSUE TITLE
Run failing is some OA11 from Wales and England

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/spc-hpc-pipeline#19]
This issue has been seen in *some* Wales regions: e.g. *W06000004* and *W06000019* (there might be others, these are the ones that i've seen fail. 

Failing in the `household_microsynth` step, with error:

`...............Traceback (most recent call last):
  File "/mnt/batch/tasks/workitems/SPCJobTest_England10/job-1/Task5_W06000019/wd/household_microsynth/scripts/run_microsynth.py", line 100, in do_hh
    msynth.run()
  File "/mnt/batch/tasks/workitems/SPCJobTest_England10/job-1/Task5_W06000019/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/household_microsynth-0.0.1-py3.9.egg/household_microsynth/household.py", line 71, in run
    self.__add_households(area, constraints)
  File "/mnt/batch/tasks/workitems/SPCJobTest_England10/job-1/Task5_W06000019/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/household_microsynth-0.0.1-py3.9.egg/household_microsynth/household.py", line 143, in __add_households
    p0 = humanleague.qisi(constraints, [np.array([0, 1, 2]), np.array([0, 3, 2]), m4408dim], [m4404, m4405, m4408])
RuntimeError: pick failed: 0.000000 from [0.000000, 0.000000, 0.000000, 0.000000, 0.000000]
`

More details in running logs from Azure:
[stderr_W06000019.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10184789/stderr_Wales.txt)
[stdout_W06000019.txt](https://github.com/alan-turing-institute/spc-hpc-pipeline/files/10184790/stdout_Wales.txt)

**Comment by crangelsmith** [comment]
Update with list of LADs where this is an issue:

- E07000238

**Comment by crangelsmith** [comment]
After some investigations, it turns out that the problem occurs [in line 143](https://github.com/nismod/household_microsynth/blob/e732bfa702972f2b72c94fb3cf878556ac54eb06/household_microsynth/household.py#L143) of the household.py script.

If we look more in detail, the next lines in the script ([line 147](https://github.com/nismod/household_microsynth/blob/e732bfa702972f2b72c94fb3cf878556ac54eb06/household_microsynth/household.py#L147)) deals with convergence issues from line 143. I'm not sure if what we observe from line 143 is a conversion error but looks kind of like it (maybe is failing instead of returning the right error message).

If this was the case, the fix is simple, replacing line 143 with the following:

``` 
try:
    p0 = humanleague.qisi(constraints, [np.array([0, 1, 2]), np.array([0, 3, 2]), m4408dim], [m4404, m4405, m4408])
except RuntimeError:
    p0 = None
```

this solves the problem because it makes it a convergence issue, and line [149](https://github.com/nismod/household_microsynth/blob/e732bfa702972f2b72c94fb3cf878556ac54eb06/household_microsynth/household.py#L149) runs without problems.

I have tested this locally with some of the failing LADs (W06000004, E07000238) and runs successfully.

**Comment by AoifeHughes** [comment]
the library which this depends on has an invalid C function which fails to return anything in certain conditions, related to the previous comment: https://github.com/virgesmith/humanleague/blob/7ba7203ed79ff1f3ab33cda812bd45335a3a5876/src/QISI.cpp#L23 - As Camila has mentioned, the easiest fix is to update household.py rather than dig into 2nd order libraries.
